-- Initial PostgreSQL schema for the merchant module.
-- Create-only migration; no seed data.
CREATE TABLE merchant_accounts (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    reviewed_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    lifecycle_reason varchar(1000),
    address_city varchar(255),
    address_country_code varchar(255),
    address_line1 varchar(255),
    address_line2 varchar(255),
    address_postal_code varchar(255),
    address_region varchar(255),
    applicant_user_id varchar(255) not null,
    contact_email varchar(255),
    contact_phone varchar(255),
    display_name varchar(255) not null,
    legal_name varchar(255),
    merchant_type varchar(255) not null check (merchant_type in ('FIRST_PARTY_RETAILER','THIRD_PARTY','C2C_SELLER')),
    registration_country_code varchar(255),
    registration_number varchar(255),
    reviewed_by varchar(255),
    status varchar(255) not null check (status in ('DRAFT','PENDING_REVIEW','CHANGES_REQUESTED','ACTIVE','SUSPENDED','REJECTED','CLOSED')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE merchant_members (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    invitation_expires_at timestamp(6) with time zone,
    joined_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    access_provisioning_status varchar(32) not null check (access_provisioning_status in ('PENDING','ACTIVE','FAILED')),
    status varchar(32) not null check (status in ('INVITED','ACTIVE','REMOVED')),
    role varchar(64) not null,
    access_provisioning_error varchar(255),
    invited_by varchar(255),
    merchant_id varchar(255) not null,
    user_id varchar(255) not null,
    uuid varchar(255) not null unique,
    primary key (id),
    constraint uk_merchant_member unique (merchant_id, user_id)
);

CREATE TABLE merchant_member_authorities (
    member_id bigint not null,
    authority varchar(64) not null,
    primary key (member_id, authority),
    CONSTRAINT FKpy2f3sxxww7perpjtds4f6tdr FOREIGN KEY (member_id) REFERENCES merchant_members
);

CREATE TABLE merchant_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE TABLE role_declaration_publication (
    declaration_revision integer not null,
    last_enqueued_at timestamp(6) with time zone,
    lease_until timestamp(6) with time zone,
    version bigint not null,
    content_digest varchar(64) not null,
    publication_key varchar(512) not null,
    primary key (publication_key)
);

CREATE TABLE security_manifest_publication (
    security_revision integer not null,
    last_enqueued_at timestamp(6) with time zone,
    lease_until timestamp(6) with time zone,
    version bigint not null,
    content_digest varchar(255) not null,
    module_key varchar(255) not null,
    primary key (module_key)
);

CREATE TABLE storefront_channel_brand (
    storefront_id bigint not null,
    sales_channel_id varchar(255) not null,
    primary key (storefront_id)
);

CREATE TABLE storefronts (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    lifecycle_reason varchar(1000),
    merchant_id varchar(255) not null,
    name varchar(255) not null,
    slug varchar(255) not null unique,
    status varchar(255) not null check (status in ('DRAFT','ACTIVE','SUSPENDED','CLOSED')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE INDEX idx_merchant_applicant on merchant_accounts (applicant_user_id);
CREATE INDEX idx_merchant_status on merchant_accounts (status);
CREATE INDEX idx_merchant_members_merchant on merchant_members (merchant_id);
CREATE INDEX idx_merchant_members_user on merchant_members (user_id);
CREATE INDEX idx_merchant_members_status on merchant_members (status);
CREATE INDEX idx_merchant_members_prov_status on merchant_members (access_provisioning_status);
CREATE INDEX idx_merchant_outbox_status_available on merchant_outbox_events (status, available_at);
CREATE INDEX idx_merchant_outbox_claimed_at on merchant_outbox_events (claimed_at);
CREATE INDEX idx_merchant_outbox_aggregate on merchant_outbox_events (aggregate_type, aggregate_id);
CREATE INDEX idx_storefront_merchant on storefronts (merchant_id);
CREATE INDEX idx_storefront_status on storefronts (status);
