-- Initial PostgreSQL schema for the workflows module.
-- Create-only migration; no seed data.
CREATE TABLE workflow_correlation (
    workflow_id varchar(64) not null,
    step varchar(128) not null,
    workflow_name varchar(128) not null,
    correlation_key varchar(256) not null,
    primary key (workflow_name, correlation_key)
);

CREATE TABLE workflow_instance (
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    status varchar(32) not null check (status in ('RUNNING','WAITING_EXTERNAL','COMPLETED','FAILED','COMPENSATING','COMPENSATED')),
    id varchar(64) not null,
    correlation_id varchar(128) not null,
    current_step varchar(128),
    idempotency_key varchar(128),
    workflow_name varchar(128) not null,
    checkpoint_json TEXT,
    context_json TEXT,
    error_message TEXT,
    primary key (id)
);

CREATE TABLE workflow_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE TABLE workflow_signal_log (
    recorded_at timestamp(6) with time zone not null,
    workflow_id varchar(64) not null,
    step varchar(128) not null,
    dedup_key varchar(256) not null,
    primary key (workflow_id, step, dedup_key)
);

CREATE INDEX idx_workflow_outbox_status_available on workflow_outbox_events (status, available_at);
CREATE INDEX idx_workflow_outbox_claimed_at on workflow_outbox_events (claimed_at);
CREATE INDEX idx_workflow_outbox_aggregate on workflow_outbox_events (aggregate_type, aggregate_id);
