-- Initial PostgreSQL schema for the catalog module.
-- Create-only migration; no seed data.
CREATE TABLE catalog_merchant_availability (
    updated_at timestamp(6) with time zone not null,
    merchant_id varchar(255) not null,
    merchant_type varchar(255),
    status varchar(255) not null,
    primary key (merchant_id)
);

CREATE TABLE catalog_outbox_event (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    headers oid not null,
    last_error oid,
    payload oid not null,
    primary key (id)
);

CREATE TABLE category (
    active boolean,
    c2c_allowed boolean not null,
    depth integer,
    lft integer,
    listing_allowed boolean not null,
    rgt integer,
    id bigint generated by default as identity,
    name varchar(255),
    uuid varchar(255) unique,
    primary key (id)
);

CREATE TABLE feature (
    category_id bigint,
    id bigint generated by default as identity,
    name varchar(255),
    uuid varchar(255) unique,
    primary key (id)
);

CREATE TABLE feature_option (
    feature_id bigint,
    id bigint generated by default as identity,
    name varchar(255),
    uuid varchar(255) unique,
    primary key (id),
    CONSTRAINT FKom8srw3c2n6kp0lm7dqlpurey FOREIGN KEY (feature_id) REFERENCES feature
);

CREATE TABLE media (
    rank integer not null,
    id bigint generated by default as identity,
    content_type varchar(255),
    path varchar(255) not null,
    storage_key varchar(255) not null unique,
    type varchar(255),
    url varchar(255),
    uuid varchar(255) unique,
    primary key (id)
);

CREATE TABLE product (
    featured boolean not null,
    created_at timestamp(6) with time zone not null,
    id bigint not null,
    updated_at timestamp(6) with time zone not null,
    moderation_note varchar(500),
    category_id varchar(255) not null,
    listing_condition varchar(255),
    merchant_id varchar(255) not null,
    name varchar(255),
    slug varchar(255) unique,
    status varchar(255) not null check (status in ('DRAFT','ACTIVE','ARCHIVED','SUSPENDED')),
    uuid varchar(255) unique,
    primary key (id)
);

CREATE TABLE product_description (
    id bigint generated by default as identity,
    product_id bigint not null,
    title varchar(100),
    name varchar(120) not null,
    description varchar(255),
    uuid varchar(255) unique,
    primary key (id),
    CONSTRAINT FK9iiotbwtk1n1b6dgga729sg9q FOREIGN KEY (product_id) REFERENCES product
);

CREATE TABLE product_variant (
    manage_inventory boolean not null,
    id bigint generated by default as identity,
    product_id bigint,
    merchant_id varchar(255) not null,
    sku varchar(255) not null,
    status varchar(255) not null,
    thumbnail_media_uuid varchar(255),
    uuid varchar(255) unique,
    primary key (id),
    constraint uq_product_variant_merchant_sku unique (merchant_id, sku),
    CONSTRAINT FKgrbbs9t374m9gg43l6tq1xwdj FOREIGN KEY (product_id) REFERENCES product
);

CREATE TABLE product_feature (
    feature_id bigint,
    feature_option_id bigint,
    id bigint generated by default as identity,
    product_variant_id bigint,
    uuid varchar(255) unique,
    primary key (id),
    CONSTRAINT FKgv1xq970xwg0q5k3jn9i23cc1 FOREIGN KEY (feature_id) REFERENCES feature,
    CONSTRAINT FKr818uywbft610g9j1prpj74le FOREIGN KEY (feature_option_id) REFERENCES feature_option,
    CONSTRAINT FKpydopckbx8bk8er6q6bfn5qv4 FOREIGN KEY (product_variant_id) REFERENCES product_variant
);

CREATE TABLE product_media (
    media_id bigint not null,
    product_id bigint not null,
    primary key (media_id, product_id),
    CONSTRAINT FKqvc5ys6lm60s5vxoferrqnuj1 FOREIGN KEY (media_id) REFERENCES media,
    CONSTRAINT FKish5xtvhdauc3njtkj6j5eyjp FOREIGN KEY (product_id) REFERENCES product
);

CREATE TABLE product_sales_channel_publication (
    variant_id bigint not null,
    sales_channel_id varchar(255) not null,
    primary key (variant_id, sales_channel_id)
);

CREATE TABLE product_variant_description (
    id bigint generated by default as identity,
    product_variant_id bigint not null,
    title varchar(100),
    name varchar(120) not null,
    description varchar(255),
    uuid varchar(255) unique,
    primary key (id),
    CONSTRAINT FKdpxpc7vsn5h84o6ltyq8w774j FOREIGN KEY (product_variant_id) REFERENCES product_variant
);

CREATE TABLE product_variant_media (
    media_id bigint not null,
    variant_id bigint not null,
    primary key (media_id, variant_id),
    CONSTRAINT FKwd34cs4plq40j2s5q4le9lrp FOREIGN KEY (media_id) REFERENCES media,
    CONSTRAINT FKc7h2c6ntv21x4a5h24c0tgm3u FOREIGN KEY (variant_id) REFERENCES product_variant
);

CREATE TABLE product_variant_option (
    variant_id bigint not null,
    variant_option_id varchar(255) not null,
    variant_type_id varchar(255) not null,
    primary key (variant_id, variant_option_id, variant_type_id),
    CONSTRAINT FKplhcd8aya55o6c5b9vfwcj64x FOREIGN KEY (variant_id) REFERENCES product_variant
);

CREATE TABLE security_manifest_publication (
    security_revision integer not null,
    last_enqueued_at timestamp(6) with time zone,
    lease_until timestamp(6) with time zone,
    version bigint not null,
    content_digest varchar(255) not null,
    module_key varchar(255) not null,
    primary key (module_key)
);

CREATE TABLE TABLE_GEN (
    next_val bigint,
    sequence_name varchar(255) not null,
    primary key (sequence_name)
);

-- Required initial state for ProductEntity's Hibernate TABLE id generator.
INSERT INTO TABLE_GEN (sequence_name, next_val) VALUES ('product', 0);

CREATE TABLE variant_type (
    id bigint generated by default as identity,
    code varchar(255) unique,
    name varchar(255),
    status varchar(255),
    uuid varchar(255) unique,
    primary key (id)
);

CREATE TABLE variant_option (
    id bigint generated by default as identity,
    variant_type_id bigint not null,
    code varchar(255) unique,
    name varchar(255),
    uuid varchar(255) unique,
    primary key (id),
    CONSTRAINT FKcw5uf9ckj0w40vs1k1yehml8y FOREIGN KEY (variant_type_id) REFERENCES variant_type
);

CREATE TABLE variant_option_unit (
    id bigint generated by default as identity,
    variant_type_id bigint,
    name varchar(255),
    uuid varchar(255) unique,
    primary key (id),
    CONSTRAINT FKhghejj8u090vfdmnuu9hpwtx3 FOREIGN KEY (variant_type_id) REFERENCES variant_type
);

CREATE INDEX idx_catalog_outbox_status_available on catalog_outbox_event (status, available_at);
CREATE INDEX idx_catalog_outbox_claimed_at on catalog_outbox_event (claimed_at);
CREATE INDEX idx_catalog_outbox_aggregate on catalog_outbox_event (aggregate_type, aggregate_id);
CREATE INDEX idx_catalog_outbox_published_at on catalog_outbox_event (published_at);
CREATE INDEX leftIndex on category (lft);
CREATE INDEX depthNameLeftIndex on category (depth, name, lft);
