product:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hbm2ddl:
        auto: create
      show_sql: true
      format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: TRACE