product:
  datasource:
    url: ${PRODUCT_DATASOURCE_URL}
    username: ${PRODUCT_DATASOURCE_USERNAME}
    password: ${PRODUCT_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: ${PRODUCT_DATASOURCE_DIALECT}
      hbm2ddl:
        auto: ${PRODUCT_JPA_DDL_AUTO:create}
      show_sql: ${PRODUCT_JPA_SHOW_SQL:true}
      format_sql: true

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:TRACE}