-- Initial PostgreSQL schema for the region module.
-- Create-only migration; no seed data.
CREATE TABLE regions (
    currency_code varchar(3) not null,
    status varchar(32) not null,
    id varchar(64) not null,
    name varchar(255) not null,
    primary key (id)
);

CREATE TABLE region_countries (
    country_code varchar(2) not null,
    region_id varchar(64) not null,
    id varchar(96) not null,
    primary key (id),
    CONSTRAINT FK97moip10btpmbmys8dinaj3yu FOREIGN KEY (region_id) REFERENCES regions
);

CREATE TABLE region_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE INDEX idx_region_outbox_status_available on region_outbox_events (status, available_at);
CREATE INDEX idx_region_outbox_claimed_at on region_outbox_events (claimed_at);
CREATE INDEX idx_region_outbox_aggregate on region_outbox_events (aggregate_type, aggregate_id);
