-- Initial PostgreSQL schema for the cart module.
-- Create-only migration; no seed data.
CREATE TABLE carts (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    channel_type varchar(255) not null,
    currency_code varchar(255) not null,
    guest_token varchar(255) not null,
    region_id varchar(255),
    sales_channel_id varchar(255) not null,
    status varchar(255) not null check (status in ('OPEN','COMPLETED','ABANDONED')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE cart_lines (
    quantity integer not null,
    unit_price numeric(19,4) not null,
    cart_id bigint not null,
    id bigint generated by default as identity,
    product_id varchar(255),
    seller_id varchar(255) not null,
    sku varchar(255),
    title varchar(255),
    uuid varchar(255) not null unique,
    variant_id varchar(255) not null,
    primary key (id),
    CONSTRAINT FKl9x8x2b1f8rksdrjfimvwbw6m FOREIGN KEY (cart_id) REFERENCES carts
);

CREATE TABLE cart_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE INDEX idx_cart_outbox_status_available on cart_outbox_events (status, available_at);
CREATE INDEX idx_cart_outbox_claimed_at on cart_outbox_events (claimed_at);
CREATE INDEX idx_cart_outbox_aggregate on cart_outbox_events (aggregate_type, aggregate_id);
CREATE INDEX idx_cart_guest_channel_region on carts (guest_token, sales_channel_id, region_id, status);
