-- Initial PostgreSQL schema for the customer module.
-- Create-only migration; no seed data.
CREATE TABLE customers (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    display_name varchar(255),
    email varchar(255) not null,
    status varchar(255) not null check (status in ('ACTIVE','SUSPENDED')),
    user_id varchar(255),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE customer_addresses (
    is_default boolean not null,
    customer_id bigint not null,
    id bigint generated by default as identity,
    city varchar(255) not null,
    country varchar(255) not null,
    line1 varchar(255) not null,
    phone varchar(255) not null,
    uuid varchar(255) not null unique,
    primary key (id),
    CONSTRAINT FKrvr6wl9gll7u98cda18smugp4 FOREIGN KEY (customer_id) REFERENCES customers
);

CREATE TABLE customer_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE INDEX idx_customer_outbox_status_available on customer_outbox_events (status, available_at);
CREATE INDEX idx_customer_outbox_claimed_at on customer_outbox_events (claimed_at);
CREATE INDEX idx_customer_outbox_aggregate on customer_outbox_events (aggregate_type, aggregate_id);
CREATE INDEX idx_customer_user on customers (user_id);
CREATE INDEX idx_customer_email on customers (email);
