-- Initial PostgreSQL schema for the pricing module.
-- Create-only migration; no seed data.
CREATE TABLE price_lists (
    rules_count integer not null,
    created_at timestamp(6) with time zone not null,
    ends_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    starts_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    description text,
    status varchar(255) not null check (status in ('DRAFT','ACTIVE')),
    title varchar(255) not null,
    type varchar(255) not null check (type in ('SALE','OVERRIDE')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE price_list_rules (
    id bigint generated by default as identity,
    price_list_id bigint not null,
    attribute varchar(255) not null,
    uuid varchar(255) not null unique,
    values_json text not null,
    primary key (id),
    CONSTRAINT FK9ik8m9giptwe3wmqnwha4g9xo FOREIGN KEY (price_list_id) REFERENCES price_lists
);

CREATE TABLE price_preferences (
    is_tax_inclusive boolean not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    attribute varchar(255) not null,
    uuid varchar(255) not null unique,
    value varchar(255),
    primary key (id)
);

CREATE TABLE price_sets (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE prices (
    amount numeric(19,6) not null,
    max_quantity integer,
    min_quantity integer,
    rules_count integer not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    price_list_id bigint,
    price_set_id bigint not null,
    updated_at timestamp(6) with time zone not null,
    currency_code varchar(255) not null,
    title varchar(255),
    uuid varchar(255) not null unique,
    primary key (id),
    CONSTRAINT FKmgsve72yovkkh1xgenhx8ahcx FOREIGN KEY (price_list_id) REFERENCES price_lists,
    CONSTRAINT FKt5nydpvnoi90a24l0ee8k2esp FOREIGN KEY (price_set_id) REFERENCES price_sets
);

CREATE TABLE price_rules (
    priority integer not null,
    id bigint generated by default as identity,
    price_id bigint not null,
    attribute varchar(255) not null,
    operator varchar(255) not null check (operator in ('EQ','GT','GTE','LT','LTE')),
    uuid varchar(255) not null unique,
    value varchar(255) not null,
    primary key (id),
    CONSTRAINT FKjj6wj8j36133jsrhcibkohi07 FOREIGN KEY (price_id) REFERENCES prices
);

CREATE TABLE pricing_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE TABLE variant_price_set_links (
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    merchant_id varchar(64) not null,
    price_set_id varchar(64) not null,
    product_id varchar(64) not null,
    variant_id varchar(64) not null,
    sku varchar(128) not null,
    primary key (variant_id)
);

CREATE INDEX idx_pricing_outbox_status_available on pricing_outbox_events (status, available_at);
CREATE INDEX idx_pricing_outbox_claimed_at on pricing_outbox_events (claimed_at);
CREATE INDEX idx_pricing_outbox_aggregate on pricing_outbox_events (aggregate_type, aggregate_id);
