-- Initial PostgreSQL schema for the inventory module.
-- Create-only migration; no seed data.
CREATE TABLE bin (
    active boolean not null,
    max_capacity integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    code varchar(255) not null,
    name varchar(255),
    uuid varchar(255) not null unique,
    zone_id varchar(255) not null,
    primary key (id),
    constraint idx_bin_code_zone unique (code, zone_id)
);

CREATE TABLE inventory_item (
    damaged integer not null,
    in_transit integer not null,
    max_stock integer,
    on_hand integer not null,
    reorder_point integer not null,
    reorder_quantity integer not null,
    reserved integer not null,
    safety_stock integer not null,
    id bigint generated by default as identity,
    last_updated timestamp(6) not null,
    version bigint,
    location_id varchar(255) not null,
    merchant_id varchar(255) not null,
    product_variant_id varchar(255),
    sku varchar(255) not null,
    status varchar(255) not null check (status in ('ACTIVE','DISCONTINUED','OUT_OF_STOCK','SUSPENDED')),
    uuid varchar(255) not null unique,
    primary key (id),
    constraint idx_inventory_sku_location unique (sku, location_id)
);

CREATE TABLE inventory_outbox_event (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    headers oid not null,
    last_error oid,
    payload oid not null,
    primary key (id)
);

CREATE TABLE inventory_reservation (
    quantity integer not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    idempotency_key varchar(255),
    inventory_item_uuid varchar(255) not null,
    order_id varchar(255) not null,
    order_line_id varchar(255) not null,
    status varchar(255) not null check (status in ('ACTIVE','RELEASED','FULFILLED','EXPIRED','CANCELLED')),
    uuid varchar(255) not null unique,
    primary key (id),
    constraint idx_inventory_reservation_idempotency unique (idempotency_key)
);

CREATE TABLE location (
    active boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    city varchar(255),
    code varchar(255) not null unique,
    country varchar(255),
    merchant_id varchar(255) not null,
    name varchar(255) not null,
    postal_code varchar(255),
    state varchar(255),
    street varchar(255),
    street2 varchar(255),
    type varchar(255) not null check (type in ('WAREHOUSE','STORE')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE location_sales_channels (
    location_id bigint not null,
    sales_channel_id varchar(255) not null,
    primary key (location_id, sales_channel_id)
);

CREATE TABLE product_variant_view (
    manage_inventory boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    product_name varchar(255),
    product_uuid varchar(255) not null,
    sku varchar(255) not null,
    status varchar(255) not null,
    variant_uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE security_manifest_publication (
    security_revision integer not null,
    last_enqueued_at timestamp(6) with time zone,
    lease_until timestamp(6) with time zone,
    version bigint not null,
    content_digest varchar(255) not null,
    module_key varchar(255) not null,
    primary key (module_key)
);

CREATE TABLE stock_movement (
    on_hand_after integer not null,
    on_hand_before integer not null,
    quantity integer not null,
    quantity_after integer not null,
    quantity_before integer not null,
    reserved_after integer not null,
    reserved_before integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    created_by varchar(255),
    inventory_item_uuid varchar(255) not null,
    reference_id varchar(255),
    type varchar(255) not null check (type in ('PURCHASE_ORDER_RECEIPT','CUSTOMER_RETURN','TRANSFER_IN','INITIAL_STOCK','SALE','TRANSFER_OUT','RETURN_TO_VENDOR','WRITE_OFF','CYCLE_COUNT_ADJUSTMENT','DAMAGE_ADJUSTMENT','SHRINKAGE','IN_TRANSIT_ANNOUNCE','IN_TRANSIT_RECEIPT','RESERVATION','RESERVATION_RELEASE')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE zone (
    active boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    code varchar(255) not null,
    location_id varchar(255) not null,
    name varchar(255) not null,
    type varchar(255) not null check (type in ('PICKING','STORAGE','STAGING','RETURNS','DAMAGED','RECEIVING')),
    uuid varchar(255) not null unique,
    primary key (id),
    constraint idx_zone_code_location unique (code, location_id)
);

CREATE INDEX idx_bin_zone on bin (zone_id);
CREATE INDEX idx_inventory_sku on inventory_item (sku);
CREATE INDEX idx_inventory_location on inventory_item (location_id);
CREATE INDEX idx_inventory_seller on inventory_item (merchant_id);
CREATE INDEX idx_inventory_outbox_status_available on inventory_outbox_event (status, available_at);
CREATE INDEX idx_inventory_outbox_claimed_at on inventory_outbox_event (claimed_at);
CREATE INDEX idx_inventory_outbox_aggregate on inventory_outbox_event (aggregate_type, aggregate_id);
CREATE INDEX idx_inventory_outbox_published_at on inventory_outbox_event (published_at);
CREATE INDEX idx_inventory_reservation_inventory on inventory_reservation (inventory_item_uuid);
CREATE INDEX idx_inventory_reservation_order on inventory_reservation (order_id);
CREATE INDEX idx_location_type on location (type);
CREATE INDEX idx_product_variant_view_product on product_variant_view (product_uuid);
CREATE INDEX idx_movement_inventory on stock_movement (inventory_item_uuid);
CREATE INDEX idx_movement_reference on stock_movement (reference_id);
CREATE INDEX idx_movement_created_at on stock_movement (created_at);
CREATE INDEX idx_zone_location on zone (location_id);
