-- Initial PostgreSQL schema for the saleschannel module.
-- Create-only migration; no seed data.
CREATE TABLE sales_channel_outbox_events (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE TABLE sales_channels (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    version bigint not null,
    merchant_id varchar(255),
    name varchar(255) not null,
    owner varchar(255) not null check (owner in ('SELLER','PLATFORM')),
    status varchar(255) not null check (status in ('ENABLED','DISABLED')),
    type varchar(255) not null check (type in ('WEBSITE','MARKETPLACE','POS')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE security_manifest_publication (
    security_revision integer not null,
    last_enqueued_at timestamp(6) with time zone,
    lease_until timestamp(6) with time zone,
    version bigint not null,
    content_digest varchar(255) not null,
    module_key varchar(255) not null,
    primary key (module_key)
);

CREATE INDEX idx_sales_channel_outbox_status_available on sales_channel_outbox_events (status, available_at);
CREATE INDEX idx_sales_channel_outbox_claimed_at on sales_channel_outbox_events (claimed_at);
CREATE INDEX idx_sales_channel_outbox_aggregate on sales_channel_outbox_events (aggregate_type, aggregate_id);
CREATE INDEX idx_sales_channel_merchant on sales_channels (merchant_id);
CREATE INDEX idx_sales_channel_type on sales_channels (type);
CREATE INDEX idx_sales_channel_status on sales_channels (status);
