#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.run/store-dev.env"

mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<'EOF'
SPRING_PROFILES_ACTIVE=dev

# logger.*
LOGGER_BACKEND=slf4j
LOGGER_LEVEL=INFO
LOGGER_FAIL_ON_MISSING_BACKEND=true

# dev DB
# Catalog datasource properties
CATALOG_DATASOURCE_URL=jdbc:h2:mem:catalog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
CATALOG_DATASOURCE_USERNAME=admin
CATALOG_DATASOURCE_PASSWORD=123
CATALOG_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
CATALOG_DATASOURCE_DIALECT=org.hibernate.dialect.H2Dialect
CATALOG_JPA_DDL_AUTO=update
CATALOG_JPA_SHOW_SQL=false
CATALOG_JPA_FORMAT_SQL=true
CATALOG_OUTBOX_FIXED_DELAY_MS=5000
CATALOG_OUTBOX_CLEANUP_FIXED_DELAY_MS=300000
CATALOG_OUTBOX_BATCH_SIZE=20
CATALOG_OUTBOX_RETRY_DELAY_MS=30000
CATALOG_OUTBOX_CLAIM_TIMEOUT_MS=120000
CATALOG_OUTBOX_RETENTION_MS=604800000

# Inventory datasource properties
INVENTORY_DATASOURCE_URL=jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
INVENTORY_DATASOURCE_USERNAME=admin
INVENTORY_DATASOURCE_PASSWORD=123
INVENTORY_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
INVENTORY_DATASOURCE_DIALECT=org.hibernate.dialect.H2Dialect
INVENTORY_JPA_DDL_AUTO=update
INVENTORY_JPA_SHOW_SQL=false
INVENTORY_JPA_FORMAT_SQL=true
INVENTORY_OUTBOX_FIXED_DELAY_MS=5000
INVENTORY_OUTBOX_CLEANUP_FIXED_DELAY_MS=300000
INVENTORY_OUTBOX_BATCH_SIZE=20
INVENTORY_OUTBOX_RETRY_DELAY_MS=30000
INVENTORY_OUTBOX_CLAIM_TIMEOUT_MS=120000
INVENTORY_OUTBOX_RETENTION_MS=604800000

# logger
LOGGER_BACKEND=console
LOGGER_LEVEL=INFO
LOGGER_FAIL_ON_MISSING_BACKEND=false
LOGGER_FILE_PATH=logs
LOGGER_FILE_NAME=store.log


EOF

set -a
source "$ENV_FILE"
set +a

exec "$ROOT/mvnw" -pl store spring-boot:run
