-- Initial PostgreSQL schema for the identity module.
-- Create-only migration; no seed data.
CREATE TABLE roles (
    active boolean not null,
    assignable boolean not null,
    id bigint generated by default as identity,
    code varchar(255) not null unique,
    description varchar(255),
    name varchar(255) not null,
    role_kind varchar(255) not null check (role_kind in ('SYSTEM','CUSTOM')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    email varchar(255) not null unique,
    password_hash varchar(255),
    status varchar(255) not null check (status in ('ACTIVE','PENDING_APPROVAL','SUSPENDED')),
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE access_assignments (
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    role_id bigint not null,
    updated_at timestamp(6) with time zone not null,
    user_id bigint not null,
    assigned_by varchar(255),
    scope_id varchar(255) not null,
    scope_key varchar(255) not null,
    status varchar(255) not null check (status in ('ACTIVE','SUSPENDED','REVOKED','EXPIRED')),
    uuid varchar(255) not null unique,
    primary key (id),
    CONSTRAINT FKm8ixhkb34qq5tjkvo6v66q225 FOREIGN KEY (role_id) REFERENCES roles,
    CONSTRAINT FKognxd16r1puqav2ebh56qq0m3 FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE access_invitations (
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    role_id bigint not null,
    updated_at timestamp(6) with time zone not null,
    token_hash varchar(64) not null unique,
    accepted_by varchar(255),
    invited_by varchar(255) not null,
    invitee_email varchar(255) not null,
    scope_id varchar(255) not null,
    scope_key varchar(255) not null,
    status varchar(255) not null check (status in ('PENDING','ACCEPTED','CANCELLED','EXPIRED')),
    uuid varchar(255) not null unique,
    primary key (id),
    CONSTRAINT FKaaas6e88k4uyxem0pgk987ys2 FOREIGN KEY (role_id) REFERENCES roles
);

CREATE TABLE authorities (
    active boolean not null,
    source_revision integer not null,
    id bigint generated by default as identity,
    category varchar(255) not null,
    code varchar(255) not null unique,
    description varchar(255),
    name varchar(255) not null,
    owner_key varchar(255) not null,
    provider_lifecycle varchar(255) not null,
    uuid varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE external_entitlement_mappings (
    id bigint generated by default as identity,
    role_id bigint not null,
    entitlement varchar(255) not null,
    issuer varchar(255) not null,
    primary key (id),
    unique (issuer, entitlement, role_id),
    CONSTRAINT FKk0afoks9k71uymlgn73xx1dh9 FOREIGN KEY (role_id) REFERENCES roles
);

CREATE TABLE external_identities (
    id bigint generated by default as identity,
    linked_at timestamp(6) not null,
    user_id bigint not null,
    issuer varchar(255) not null,
    subject varchar(255) not null,
    primary key (id),
    unique (issuer, subject),
    CONSTRAINT FKihk75aenimxpvt76b6lv2ento FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE identity_outbox_event (
    attempt_count integer not null,
    event_version integer not null,
    available_at timestamp(6) not null,
    claimed_at timestamp(6),
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    published_at timestamp(6),
    aggregate_id varchar(255) not null,
    aggregate_type varchar(255) not null,
    claim_token varchar(255),
    event_type varchar(255) not null,
    headers text not null,
    last_error text,
    payload text not null,
    status varchar(255) not null check (status in ('NEW','PROCESSING','PUBLISHED','FAILED')),
    primary key (id)
);

CREATE TABLE refresh_sessions (
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    last_used_at timestamp(6) with time zone,
    replaced_by_id bigint,
    revoked_at timestamp(6) with time zone,
    user_id bigint not null,
    token_hash varchar(64) not null unique,
    assignment_uuid varchar(255),
    scope_id varchar(255),
    scope_key varchar(255),
    token_family_id varchar(255) not null,
    primary key (id),
    CONSTRAINT FK9ndfh1op1iy3xuqyi6gxkseg0 FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE role_authorities (
    authority_id bigint not null,
    role_id bigint not null,
    primary key (authority_id, role_id),
    CONSTRAINT FKpmbd5d32ddnedap7prbfhwuy2 FOREIGN KEY (authority_id) REFERENCES authorities,
    CONSTRAINT FKffl6vh23qrnrld2sxfhtjhbkm FOREIGN KEY (role_id) REFERENCES roles
);

CREATE TABLE role_declaration_conflict (
    revision integer not null,
    id bigint generated by default as identity,
    recorded_at timestamp(6) with time zone not null,
    existing_digest varchar(64),
    supplied_digest varchar(64) not null,
    event_id varchar(255) not null,
    owner varchar(255) not null,
    payload TEXT not null,
    reason TEXT not null,
    role_code varchar(255) not null,
    primary key (id),
    constraint uk_role_declaration_conflict_event_digest unique (event_id, supplied_digest)
);

CREATE TABLE role_declaration_inbox (
    revision integer not null,
    received_at timestamp(6) with time zone not null,
    status varchar(40) not null,
    content_digest varchar(64) not null,
    event_id varchar(255) not null,
    owner varchar(255) not null,
    role_code varchar(255) not null,
    primary key (event_id)
);

CREATE TABLE role_declaration_revision (
    revision integer not null,
    applied_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    received_at timestamp(6) with time zone not null,
    row_version bigint not null,
    status varchar(40) not null,
    content_digest varchar(64) not null,
    event_id varchar(255) not null,
    owner varchar(255) not null,
    payload TEXT not null,
    reason TEXT,
    role_code varchar(255) not null,
    primary key (id),
    constraint uk_role_declaration_revision unique (owner, role_code, revision)
);

CREATE TABLE role_declaration_state (
    applied_revision integer not null,
    row_version bigint not null,
    applied_digest varchar(64) not null,
    assignment_scope_key varchar(255) not null,
    owner varchar(255) not null,
    role_code varchar(255) not null,
    primary key (role_code)
);

CREATE TABLE role_delegation_rules (
    delegated_role_id bigint not null,
    delegator_role_id bigint not null,
    id bigint generated by default as identity,
    primary key (id),
    constraint uk_role_delegation_rule unique (delegator_role_id, delegated_role_id),
    CONSTRAINT FKp6qoh00wksky7obriy92n2c8a FOREIGN KEY (delegated_role_id) REFERENCES roles,
    CONSTRAINT FKclvw7uj68o4uyyg9gd1sb6yuu FOREIGN KEY (delegator_role_id) REFERENCES roles
);

CREATE TABLE security_catalog_state (
    catalog_revision bigint not null,
    id bigint not null,
    row_version bigint not null,
    primary key (id)
);

CREATE TABLE security_manifest_conflict (
    revision integer not null,
    id bigint generated by default as identity,
    received_at timestamp(6) with time zone not null,
    content_digest varchar(255) not null,
    error_code varchar(255),
    event_id varchar(255) not null,
    module_key varchar(255) not null,
    payload TEXT,
    status varchar(255) not null,
    supplied_digest varchar(255),
    primary key (id)
);

CREATE TABLE security_manifest_inbox (
    revision integer not null,
    processed_at timestamp(6) with time zone not null,
    content_digest varchar(255) not null,
    error_code varchar(255),
    event_id varchar(255) not null,
    module_key varchar(255) not null,
    status varchar(255) not null,
    primary key (event_id)
);

CREATE TABLE security_manifest_module (
    applied_revision integer not null,
    row_version bigint not null,
    applied_digest varchar(255),
    module_key varchar(255) not null,
    primary key (module_key)
);

CREATE TABLE security_manifest_publication (
    security_revision integer not null,
    last_enqueued_at timestamp(6) with time zone,
    lease_until timestamp(6) with time zone,
    version bigint not null,
    content_digest varchar(255) not null,
    module_key varchar(255) not null,
    primary key (module_key)
);

CREATE TABLE security_manifest_revision (
    revision integer not null,
    applied_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    received_at timestamp(6) with time zone not null,
    row_version bigint not null,
    content_digest varchar(255) not null,
    dependency_error varchar(255),
    event_id varchar(255) not null,
    module_key varchar(255) not null,
    payload TEXT not null,
    status varchar(255) not null,
    primary key (id),
    constraint uk_security_manifest_revision unique (module_key, revision)
);

CREATE TABLE security_scope_definitions (
    active boolean not null,
    manifest_version integer not null,
    source_revision integer not null,
    id bigint generated by default as identity,
    row_version bigint not null,
    module_key varchar(255) not null,
    parent_scope_key varchar(255),
    provider_lifecycle varchar(255) not null,
    scope_key varchar(255) not null,
    primary key (id),
    constraint uk_security_scope_key unique (scope_key)
);

CREATE INDEX idx_access_assignment_user_role on access_assignments (user_id, role_id);
CREATE INDEX idx_access_assignment_scope on access_assignments (scope_key, scope_id);
CREATE INDEX idx_access_invitation_email on access_invitations (invitee_email);
CREATE INDEX idx_access_invitation_scope on access_invitations (scope_key, scope_id);
CREATE INDEX idx_identity_outbox_status_available on identity_outbox_event (status, available_at);
CREATE INDEX idx_identity_outbox_claimed_at on identity_outbox_event (claimed_at);
CREATE INDEX idx_identity_outbox_aggregate on identity_outbox_event (aggregate_type, aggregate_id);
CREATE INDEX idx_identity_outbox_published_at on identity_outbox_event (published_at);
