CREATE TABLE IF NOT EXISTS security_manifest_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key VARCHAR(128) NOT NULL,
    revision INTEGER NOT NULL,
    content_digest VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    dependency_error VARCHAR(256),
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_security_manifest_revision UNIQUE (module_key, revision)
);

CREATE TABLE IF NOT EXISTS security_manifest_module (
    module_key VARCHAR(128) PRIMARY KEY,
    applied_revision INTEGER NOT NULL DEFAULT 0,
    applied_digest VARCHAR(128),
    row_version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS security_catalog_state (
    id BIGINT PRIMARY KEY,
    catalog_revision BIGINT NOT NULL DEFAULT 0,
    row_version BIGINT NOT NULL DEFAULT 0
);

INSERT INTO security_catalog_state (id, catalog_revision, row_version)
VALUES (1, 0, 0)
ON CONFLICT (id) DO NOTHING;
