CREATE TABLE IF NOT EXISTS security_manifest_conflict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    module_key VARCHAR(128) NOT NULL,
    revision INTEGER NOT NULL,
    content_digest VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_code VARCHAR(128),
    received_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_security_manifest_conflict_event
    ON security_manifest_conflict (event_id, received_at);
